[package]
name = "ellington"
version = "0.1.0"
authors = ["Adam Harries <harries.adam@gmail.com>"]
build = "build.rs"

[dependencies]
plist = "0.2"
histogram = "0.6.9"
byteorder = "1"
memmap = "0.6.2"
clap = {version = "2.31.2", features = ["yaml"]}
rand = "0.5.2"
itertools = "0.7.8"
id3 = "0.2.2"
url = "1.7.0"
percent-encoding = "1.0.1"
serde = "1.0.66"
serde_derive= "1.0.66"
serde_json = "1.0"
regex = "1.0.1"
lazy_static = "1.0.1"
taglib = "0.2.0"
walkdir = "2"
taglib-rs = { git = "https://github.com/AdamHarries/taglib-rs.git" }
log = "0.4"
env_logger  = "0.5.1"
slog = "2.2.3"
slog-term = "2.4.0"
slog-scope = "4.0.1"